config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_scope :user do
    devise_for :users, :controllers => {
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks',
      :sessions => "users/sessions",
      :passwords => "passwords"
    }
  end

  match '/users/:id/finish_signup' => 'users#finish_signup',
    via: [:get, :patch], :as => :finish_signup

  resources :users, :only => [:update_avatar] do
    collection do
      post :update_avatar
    end
  end

  draw :user
  draw :admin
  draw :photographer
  draw :api

  match  '/system/photos/*' => 'pages#block', via: [:get, :post]
  match  '/system/videos/*' => 'pages#block', via: [:get, :post]

  match '/thumbs-speed' => 'thumbs_speed#photos', via: [:get]

  resources :help_tooltips do
    post :manage, on: :collection
  end
  resources :translations do
  end

end

app/models/translation.rb
class Translation < ActiveRecord::Base

end

app/controllers/api/translations_controller.rb
class Api::TranslationsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    data = {
      locale: I18n.locale,
      key: params[:key],
      content: I18n.t(params[:key])
    }
    render json: data
  end

  def update
    I18n.backend.store_translations(params[:locale], {params[:key] => params[:content]}, :escape => false)
    render json: {status: :ok}
  end

  protected
  def verify_admin
    unless current_user.admin?
      render json: "not authorized!", status: 401
    end
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def index
  end

  def create
    I18n.backend.store_translations(params[:locale], {params[:key] => params[:value]}, :escape => false)
    redirect_to translations_url, :notice => "Added translation"
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/index.html.haml
%h1= t '.translations'
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr

%ul

%h2= t '.add_translation'
= form_tag translations_path do
  %p
    = label_tag :locale
    %br/
    = text_field_tag :locale
  %p
    = label_tag :key
    %br/
    = text_field_tag :key
  %p
    = label_tag :value
    %br/
    = text_field_tag :value
  %p= submit_tag t('.submit')


%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr
%p{editable: true, :'data-key'=> 'welcome'}
  = t "welcome"
%hr