config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_scope :user do
    devise_for :users, :controllers => {
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks',
      :sessions => "users/sessions",
      :passwords => "passwords"
    }
  end

  match '/users/:id/finish_signup' => 'users#finish_signup',
    via: [:get, :patch], :as => :finish_signup

  resources :users, :only => [:update_avatar] do
    collection do
      post :update_avatar
    end
  end

  draw :user
  draw :admin
  draw :photographer
  draw :api

  match  '/system/photos/*' => 'pages#block', via: [:get, :post]
  match  '/system/videos/*' => 'pages#block', via: [:get, :post]

  match '/thumbs-speed' => 'thumbs_speed#photos', via: [:get]

  resources :help_tooltips do
    post :manage, on: :collection
  end
  resources :translations do
  end

end

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('.log_in'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('.sign_up'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('.forgot_password'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_provider', provider: provider.to_s.titleize),
      omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>